### ISSUE TITLE
update to target 34 SDK, crashed.

### ISSUE THREAD

**Issue by lomolomo2** [lomorage/lomo-android-apk-release#12]
java.lang.ClassCastException
	at android.support.v4.media.session.MediaControllerCompat$MediaControllerImplApi21$ExtraBinderRequestResultReceiver$$ExternalSyntheticThrowCCEIfNotNull0.m(SourceFile:1)
	at com.lomoware.lomorage.network.LomoApi.getNewInst(SourceFile:126)
	at com.lomoware.lomorage.logic.LomodServerUtils.isLomodInited(SourceFile:233)
	at com.lomoware.lomorage.ui.login.LoginActivity$onLomodInfoGot$1$1.invokeSuspend(SourceFile:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:129)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)
	Suppressed: Y4.i: [L0{Cancelling}@4d27bc, Dispatchers.Main]

**Comment by lomolomo2** [comment]
java.lang.ClassCastException
	at androidx.appcompat.app.ToolbarActionBar$$ExternalSyntheticThrowCCEIfNotNull0.m(SourceFile:1)
	at com.lomoware.lomorage.network.LomoApi.getNewInst(SourceFile:123)
	at com.lomoware.lomorage.ui.login.LoginViewModel.doLogin(SourceFile:554)
	at com.lomoware.lomorage.ui.login.LoginViewModel.access$doLogin(SourceFile:1)
	at com.lomoware.lomorage.ui.login.LoginViewModel$loginEx$1.invokeSuspend(SourceFile:54)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:129)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: X4.i: [L0{Cancelling}@8ad6314, Dispatchers.Main]

**Comment by lomolomo2** [comment]
https://github.com/square/retrofit/issues/4134

**Comment by lomolomo2** [comment]
update from google store.
