### ISSUE TITLE
Failed uploading

### ISSUE THREAD

**Issue by lomolomo2** [lomorage/lomo-android-apk-release#13]
1732609042898,2024.11.26 00:17:22.898,INFO,Lomorage-UploadMgr.kt:invoke(617),patchupg Progress: PXL_20241125_041101944.TS.mp4: 177804643: 38.956528
1732609063757,2024.11.26 00:17:43.757,INFO,Lomorage-UploadMgr.kt:invoke(617),patchupg Progress: PXL_20241125_041101944.TS.mp4: 177804643: 39.958614
1732609072399,2024.11.26 00:17:52.399,DEBUG,Lomorage-MainActivity.kt:onPause(2294),main>>life>>onPause
1732609076798,2024.11.26 00:17:56.798,DEBUG,Lomorage-MainActivity.kt:onResume(2281),main>>life>>onResume true
1732609080427,2024.11.26 00:18:00.427,INFO,Lomorage-UploadMgr.kt:invoke(617),patchupg Progress: PXL_20241125_041101944.TS.mp4: 177804643: 40.960705
1732609080520,2024.11.26 00:18:00.520,DEBUG,Lomorage-MainActivity.kt:onPause(2294),main>>life>>onPause
1732609081522,2024.11.26 00:18:01.522,INFO,Lomorage-UploadMgr.kt:invoke(617),patchupg Progress: PXL_20241125_041101944.TS.mp4: 177804643: 41.962795
1732609082424,2024.11.26 00:18:02.424,INFO,Lomorage-UploadMgr.kt:invoke(617),patchupg Progress: PXL_20241125_041101944.TS.mp4: 177804643: 42.96488
1732609083264,2024.11.26 00:18:03.264,INFO,Lomorage-UploadMgr.kt:invoke(617),patchupg Progress: PXL_20241125_041101944.TS.mp4: 177804643: 43.96697
1732609084714,2024.11.26 00:18:04.714,INFO,Lomorage-UploadMgr.kt:invoke(617),patchupg Progress: PXL_20241125_041101944.TS.mp4: 177804643: 44.96906
1732609085669,2024.11.26 00:18:05.669,ERROR,Lomorage-UploadMgr.kt:patchUploadAsset(648),patchupg>> exception = unexpected end of stream
1732609085942,2024.11.26 00:18:05.942,INFO,Lomorage-UploadMgr.kt:isUploadedEx(489),begin...
1732609116040,2024.11.26 00:18:36.040,ERROR,Lomorage-UploadMgr.kt:isUploadedEx(541),upg>> isUploadedEx: exception: failed to connect to /192.168.1.1 (port 8000) from /192.168.1.228 (port 49792) after 30000ms, stack = java.net.SocketTimeoutException: failed to connect to /192.168.1.1 (port 8000) from /192.168.1.228 (port 49792) after 30000ms <br> 	at libcore.io.IoBridge.connectErrno(IoBridge.java:235) <br> 	at libcore.io.IoBridge.connect(IoBridge.java:179) <br> 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142) <br> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390), id = 1000018296, file = /storage/emulated/0/DCIM/Camera/PXL_20241125_040508421.TS.mp4, hash = 5dcb9311319a119bffd04cfd2e670645a56212f8
1732609116068,2024.11.26 00:18:36.068,INFO,Lomorage-UploadMgr.kt:isUploadedEx(489),begin...
1732609146099,2024.11.26 00:19:06.099,ERROR,Lomorage-UploadMgr.kt:isUploadedEx(541),upg>> isUploadedEx: exception: failed to connect to /192.168.1.1 (port 8000) from /192.168.1.228 (port 41754) after 30000ms, stack = java.net.SocketTimeoutException: failed to connect to /192.168.1.1 (port 8000) from /192.168.1.228 (port 41754) after 30000ms <br> 	at libcore.io.IoBridge.connectErrno(IoBridge.java:235) <br> 	at libcore.io.IoBridge.connect(IoBridge.java:179) <br> 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142) <br> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390), id = 1000014651, file = /storage/emulated/0/DCIM/Camera/PXL_20240504_040854387.TS.mp4, hash = 7e976eecd96b2fc240904bd5654a5448a638a6b6

**Comment by lomolomo2** [comment]
id = 1000018297, file = /storage/emulated/0/DCIM/Camera/PXL_20241125_041101944.TS.mp4, hash = **e05783b455feba72e3ec932bc204d5035ce279e4**


![image](https://github.com/user-attachments/assets/9b019e4b-e50b-4bac-833b-f3c42b68000d)
